name: Terraform Apply

on:
    push:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
            ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }} 
            ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
            ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            TF_IN_AUTOMATIOn: true

        steps:
        - name: "Checkout repository"
          uses: "actions/checkout@v2"

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: terraform init -input=false
          working-directory: ./tf

        - id: plan
          run: terraform plan -input=false -out=tfplan
          working-directory: ./tf
           
        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan
          working-directory: ./tf